<a href="https://colab.research.google.com/github/Abhay-211/pytorch/blob/main/math_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR

*   ADD,SUBTRACT,DIVIDE,MULTIPLY,REMAINDERS,EXPONENT

*   SHORTHAND AND LONGHAND
REASSIGNMENT



In [ ]:
import torch
import numpy as np

In [ ]:
tensor_a =torch.tensor([1,2,3,4])
tensor_b =torch.tensor([5,6,7,8])

In [ ]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
## addition Longhand
torch.add(tensor_a , tensor_b )

tensor([ 6,  8, 10, 12])

In [ ]:
#subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
#subb function
torch.sub(tensor_b , tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
#multiplication longhand
torch.mul(tensor_a , tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
#divison longhand
torch.div(tensor_b , tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# remainder function
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
# remainder longhand
torch.remainder(tensor_b , tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
#tensor exponents
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
#another way for longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a=tensor_a +tensor_b
tensor_a

tensor([11, 14, 17, 20])

In [ ]:
tensor_a

tensor([11, 14, 17, 20])