<a href="https://colab.research.google.com/github/Abhay-211/pytorch/blob/main/reshapenview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
t1=torch.arange(10)
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshapes and view

In [ ]:
t1=t1.reshape(2,5)
t1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
t3=torch.arange(10).reshape(2,5)
t3[0,1]=41
print(t3)

tensor([[ 0, 41,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])


In [ ]:
t3[1,3]=11
t3

tensor([[ 0, 41,  2,  3,  4],
        [ 5,  6,  7, 11,  9]])

In [ ]:
t3

tensor([[ 0, 41,  2,  3,  4],
        [ 5,  6,  7, 11,  9]])

In [7]:
t4=torch.arange(10)
t4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
t4=t4.reshape(2,5)
t4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
t4[:,1:]

tensor([[1, 2, 3, 4],
        [6, 7, 8, 9]])