<a href="https://colab.research.google.com/github/Abhay-211/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TENSORS


*   A torch.tensor is a multi-dimensional matrix containing elements of single data type
*   similar to Numpy Arrays, but full of fun things that make them work better on GPUs vs regulae CPUs

*   default data type of float32
*   More suitable for deep learning rhan a numpy array




In [2]:
import torch
import numpy as np

TENSORS

In [6]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 0.4536,  0.2212,  1.6620, -1.1635],
        [-1.1315, -0.3611, -0.7354,  0.1643],
        [-1.7277,  0.0333,  0.7987, -1.7121]])

In [8]:
tensor_3d= torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
tensor_ones=torch.ones(2,3,5, dtype= torch.int32)
tensor_ones

tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)